---
- name: Add OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', restic_os_variables) }}"

- name: Perform versionscheck
  ansible.builtin.include_tasks: 'versioncheck.yml'
  when: submodules_versioncheck|bool

- name: Make sure restic is available
  ansible.builtin.include_tasks: 'preperation.yml'

- name: Install restic
  ansible.builtin.include_tasks: 'install.yml'
  when: not restic_executable.stat.exists or not restic_installed.stat.exists

- name: Configure restic
  ansible.builtin.include_tasks: 'configure.yml'

- name: Create backup script
  ansible.builtin.include_tasks: 'backup.yml'
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_version: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'

- name: Create restic systemd timer
  ansible.builtin.include_tasks: 'timer.yml'
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_version: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'

- name: Configure prometheus metrics
  include_tasks: prometheus.yml
  when: metrics_dir is defined
  
