---
- name: Metrics - deploy scripts
  copy:
    src: "{{ item }}"
    dest: "{{ restic_script_dir }}/{{ item }}"
    mode: 0755
  with_items:
  - restic_stats.py

- name: Metrics - schedule run via crontab
  cron:
    name: restic metrics
    job: "{{ restic_script_dir }}/restic_stats.py {{ metrics_dir }}/summary-*.json > {{ restic_log_dir }}/restic_stats.prom &> /dev/null"
    minute: "*/10"

