---
- name: Metrics - deploy scripts
  copy:
    src: "{{ item }}"
    dest: "{{ restic_script_dir }}/{{ item }}"
    mode: 0755
  with_items:
  - restic_stats.py
  - restis_stats.sh

- name: Metrics - schedule run via crontab
  cron:
    name: restic metrics
    job: "{{ restic_script_dir }}/restic_stats.sh {{ restic_log_dir }} {{ metrics_dir }} &> /dev/null"
    minute: "*/10"

